apiVersion: v1
kind: Namespace
metadata:
  name: lab-5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    lab: lab-5
  name: temperamental
  namespace: lab-5
spec:
  replicas: 2
  selector:
    matchLabels:
      lab: lab-5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        lab: lab-5
    spec:
      containers:
        - image: docker.io/bryanl/k8st-temperamental:latest
          name: app
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: temperamental
  namespace: lab-5
  labels:
    lab: lab-5
spec:
  rules:
    - host: app.local
      http:
        paths:
          - backend:
              serviceName: temperamental
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: temperamental
  namespace: lab-5
  labels:
    lab: lab-5
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    lab: lab-5
